
#spring.datasource.url=jdbc:mysql://localhost:3306/jbdl33_jpa?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/library_jbdl36?createDatabaseIfNotExist=true
    username: root
    password: password


